openapi: 3.0.0
info:
  title: Lorcana API
  version: 1.0.0
servers:
  - url: https://api.lorcana-api.com
paths:
  /cards:
    get:
      summary: Get Lorcana cards (optionally filter by name)
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Name of the card (exact match)
      responses:
        '200':
          description: A list of Lorcana cards
          content:
            application/json:
              schema:
                type: array
                items:
                  type: o
